### ISSUE TITLE
Joomla 5 compatibility

### ISSUE THREAD

**Issue by crimle** [aranemac/jbsAccordion#4]
I very much appreciate this plugin. Unfortunately, it is not fully compatible with Joomla 5. As soon as the plg_behaviour_compat is disabled, the website displays an error. May I hope for an update? Thank you very much.

**Comment by aranemac** [comment]
Sorry, but as I don't use Joomla 5 yet, I am not able to test it.
Perhaps someone can fork and fix it.

**Comment by aranemac** [comment]
Fixed it anyway. ;-)
It was only a minor issue (changed "JPlugin" to "Joomla\CMS\Plugin\CMSPlugin")

**Comment by crimle** [comment]
I am very grateful and happy to use this plugin.
